# Generated by Django 2.2.16 on 2022-10-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
