# Generated by Django 2.2.16 on 2022-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(blank=True, help_text='Тема поста', max_length=50, null=True, verbose_name='Тема поста'),
        ),
    ]
